key_words = [
    'trump',
    'president',
    'healthcare',
    'border',
    'wall',
    'democrat',
    'republican',
    'liberal',
    'conservative',
    'abortion',
    'clinton',
    'sanders',
    'socialist',
    'economy',
    'jobs',
    'impeach',
    'obama',
    'russia',
    'mueller',
    'collusion',
    'military',
    'budget',
    'market',
    'trade',
    'vote',
    'democracy',
    'gun',
    'agriculture',
    'women',
    'business',
    'tax',
    'medicare',
    'police',
    'immigration',
    'insurance',
    'climatechange',
    'corrupt',
    'electoralcollege',
    'judge',
    'court',
    'gerrymander',
    'pelosi',
    'mcconnell',
    'mikepence',
    'citizensunited',
    'daca',
    'dreamers',
    'lgbtq',
    'ACA',
    'scotus',
    'partisan',
    'patriot',
    'welfare',
    'privilege',
    'minority',
    'islam',
    'muslim',
    'christian',
    'god',
    'religion',
    'administration',
    'politics',
    'fair',
    'witchhunt',
    'warren',
    'biden',
    'security',
    'terrorism',
    'defense',
    'pentagon',
    'homelandsecurity',
    'senate',
    'wealth',
    'american',
    'church',
    'science',
    'stockmarket',
    'congress',
    'whitehouse',
    'constitution',
    'federal',
    'syria',
    'northkorea',
    'saudiarabia',
    'mexico',
    'debt',
    'fiscal',
    'oil',
    'media',
    'cnn',
    'fox',
    'news',
    'racist',
    'refugee',
    'education',
    'maga',
    'campaign',
    'party',
    'poll']

key_synonyms = {
    'realdonaldtrump': 'trump',
    'realdonald trump': 'trump',
    'donaldtrump': 'trump',
    'donald trump': 'trump',
    'presidenttrump': 'trump',
    'president trump': 'trump',
    'potus': 'trump',
    'health care': 'healthcare',
    'dems': 'democrat',
    'gop': 'republican',
    'left wing': 'liberal',
    'leftist': 'liberal',
    'progressive': 'liberal',
    'right wing': 'conservative',
    'abort': 'abortion',
    'bernie sanders': 'sanders',
    'bernie': 'sanders',
    ' econ ': ' economy ',
    'economics': 'economy',
    'impeachment': 'impeach',
    'barack obama': 'obama',
    'robert mueller': 'mueller',
    'armed forces': 'military',
    'armed services': 'military',
    'firearm': 'gun',
    'assault rifle': 'gun',
    'climate change': 'climatechange',
    'global warming': 'climatechange',
    'corruption': 'corrupt',
    'corrupted': 'corrupt',
    'electoral college': 'electoralcollege',
    'court justice': 'judge',
    'nancy pelosi': 'pelosi',
    'mitch mcconnell': 'mcconnell',
    'vice president mike pence': 'mikepence',
    'vice president pence': 'mikepence',
    'mike pence': 'mikepence',
    ' pence ': ' mikepence ',
    'citizens united': 'citizensunited',
    'deferred action for childhood arrivals': 'daca',
    'lgbt': 'lgbtq',
    'affordable care act': 'aca',
    'obamacare': 'aca',
    'obama care': 'aca',
    'supreme court of the united states': 'scotus',
    'us supreme court': 'scotus',
    'united states supreme court': 'scotus',
    'supreme court': 'scotus',
    'islamic': 'islam',
    'christianity': ' christian',
    'political': 'politics',
    'witch hunt': 'witchhunt',
    'elizabeth warren': 'warren',
    'counterterrorism': 'terrorism',
    'counter-terrorism': 'terrorism',
    'homeland security': 'homelandsecurity',
    'us senate': 'senate',
    'united states senate': 'senate',
    'senatorial': 'senate',
    'rich': 'wealthy',
    'wealthy': ' wealth',
    'billionaire': 'wealthy',
    'temple': 'church',
    'stock market': 'stockmarket',
    'stocks': 'stockmarket',
    'congressional': 'congress',
    'white house': 'whitehouse',
    'north korean': 'northkorea',
    'north korea': 'northkorea',
    'saudi arabian': 'saudiarabia',
    'saudi arabia': 'saudiarabia',
    ' saudi ': ' saudiarabia ',
    'mexican': 'mexico',
    'fox news': 'fox',
    'cable news network': 'cnn',
    'make america great again': 'maga'
}

#import pickle
#f = open("key_words.pkl", "wb")
#pickle.dump(key_words, f)
#f.close()

#f = open("synonym_dictionary.pkl","wb")
#pickle.dump(key_synonyms,f)
#f.close()
